export const GET_HOME_PAGE_DATA='GET_HOME_PAGE_DATA'

export const GET_CATEGORY_DATA='GET_CATEGORY_DATA'

export const GET_COUNTRTY_DATA='GET_COUNTRY_DATA'

export const GET_CONTACT_DATA='GET_CONTACT_DATA'

export const GET_STATE_DATA='GET_STATE_DATA'

export const GET_CITY_DATA='GET_CITY_DATA'

export const GET_SELLER_SIGNUP_FORM='GET_SELLER_SIGNUP_FORM'

export const GET_LOGIN_DATA='GET_LOGIN_DATA'

export const GET_SIGN_UP='GET_SIGN_UP'

export const GET_USER_PROFILE='GET_USER_PROFILE'

export const GET_USER_ADDRESS='GET_USER_ADDRESS'

export const GET_WISHLIST='GET_WISHLIST'

export const GET_NOTIFICATION='GET_NOTIFICATION'

export const GET_CART_DATA='GET_CART_DATA'

export const GET_USER_DETAIL_ADDRESS='GET_USER_DETAIL_ADDRESS'
